### ISSUE TITLE
llvm-knc

### ISSUE THREAD

**Issue by jianbinfang** [apc-llc/gcc-5.1.1-knc#1]
Hi, I wonder whether there is a llvm patch for the Xeon Phi (KNC) backend so that I can generate a native compiler for KNC with llvm.

**Comment by dmikushin** [comment]
AFAIK, Intel engineers @ LLVM are targeting KNL, bypassing KNC.

**Comment by jianbinfang** [comment]
Hi, basically I would like to build an experimental platform, but I have no KNL at hand. If there is a patch for KNC, it would be great.

**Comment by dmikushin** [comment]
The problem is that you can't "plug" KNL backend in place of KNC, because they have different (yet, a lot similar) ISA. Compiler will generate you the assembly, but it will SIGILL upon execution.

What you experimental platform is intended to do?

**Comment by jianbinfang** [comment]
Basically I would like to build an OpenCL implementation for KNC as a research experimental platform. It seems that the Intel OpenCL implementation of KNC has been deprecated. I noticed that most OCL implementations are based on LLVM. So if there is a llvm patch for KNC, it will help me a lot.

**Comment by dmikushin** [comment]
The fact that OpenCL implementations are mostly LLVM-based in a way explains why such patch is not publicly available (LLVM license permits that).
